name = "ibd-guide"
compatibility_date = "2025-06-03"
main = "./worker/index.ts"
preview_urls = true

[assets]
directory = "./dist/client/"
not_found_handling = "single-page-application"
binding = "ASSETS"
